### ISSUE TITLE
RSS support

### ISSUE THREAD

**Issue by mmgoodnow** [mmgoodnow/cross-seed#13]
Since we're connected to Jackett, we have Torznab RSS feeds available to us. It would be nice to read RSS feeds every 10 or so minutes and compare them to existing torrents. 

xmljs is probably the best lib for this. 

This will be the slightly less useful half of daemon mode.

**Comment by mmgoodnow** [comment]
As of #212, some of the logic for this is already implemented. The rest is just assembling the major building blocks: 
  - [x] RSS feed parsing (done in #179)
  - [ ] "reverse lookup" matching (in PR, #212)
  - [ ] some sort of cron system (#164)

**Comment by mmgoodnow** [comment]
@bakerboy448 as a Prowlarr dev, i've got a couple questions for you.

In Jackett, the "RSS link" seems to be just a normal Torznab search with the empty string as the query. Is that true? Are there any other differences between RSS and Torznab in Prowlarr? Maybe some extra caching given that apps tend to query the RSS feed often?

**Comment by bakerboy448** [comment]
That's correct for RSS. Same logic \*Arrs use.

Prowlarr has no cache.
